<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/11/10 0010
 * Time: 下午 1:13
 */

namespace backend\modules\fin\accountReceivable\models;


use backend\models\BaseRecord;
use backend\models\interfaces\DeleteRecordOperator;
use backend\models\UUID;

class ReceiveMoneyCompany extends BaseRecord implements DeleteRecordOperator
{
    public static function tableName()
    {
        return self::FINReceiveMoneyCompany;
    }
    
    public function getRecord($uuid) {
        if(empty($uuid)) {
            return '';
        }
        
        return self::find()->andWhere(['uuid'=>$uuid])->asArray()->one();
    }

    public function formDataPreHandler(&$formData, $record)
    {
        if(empty($record)) {
            $formData['uuid'] = UUID::getUUID();
        }
        parent::formDataPreHandler($formData, $record); // TODO: Change the autogenerated stub
    }
    
    public function receiveMoneyCompanyList() {
        return self::find()->asArray()->all();
    }

    public function insertRecord($formData)
    {
        if(empty($formData)) {
            return true;
        }

        if(!$this->updatePreHandler($formData)) {
            return true;
        }

        return $this->insert();
    }

    public function updateRecord($formData)
    {
        // TODO: Implement updateRecord() method.
    }

    public function deleteRecord($uuid)
    {
        if(empty($uuid)) {
            return true;
        }

        $record = self::find()->andWhere(['uuid'=>$uuid])->one();
        if(empty($record)) {
            return true;
        }

        return $record->delete();
    }
}