<?php

namespace backend\modules\hr\models\config;
use backend\models\Config;
use yii\helpers\Json;
class EmployeeBasicConfig extends Config
{
    public $extraConfig;
    const AskLeaveApplying = 1;
    const AskLeaveSucceed = 2;
    const AskLeaveRefused = 3;

    public function init()
    {
        $this->extraConfig = [
            'ask_for_leave_status'=>[
                self::AskLeaveApplying => '请假申请中',
                self::AskLeaveSucceed => '请假成功',
                self::AskLeaveRefused => '请假未通过',
            ]
        ];
        $this->key = 'employee_basic_config';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function updateConfig($formData)
    {
        $config = $this->generateConfig();
        foreach($formData as $key => $item) {
            if(isset($config[$key])) unset($config[$key]);
            $value = [];
            foreach ($item as $k => $itemValue) {
                if (empty($itemValue) || $itemValue === null
                    || !isset($itemValue['key']) || empty($itemValue['key'])) {
                    unset($value[$k]);
                    continue;
                }
                $value[$itemValue['key']] = $itemValue['value'];
            }
            $config[$key] = $value;
        }

        return $this->updateRecord([
            'uuid' => md5($this->key),
            'config'=>Json::encode($config),
            'uuid_key'=>$this->key,
        ]);
    }

    public function getList($key)
    {
        $list =  parent::getList($key);
        if(empty($list)) {
            $list = isset($this->extraConfig[$key])?$this->extraConfig[$key]:[];
        }
        return $list;
    }

    public function getAppointed($key, $index)
    {
        $value =  parent::getAppointed($key, $index);
        if(empty($value)) {
            $value =  isset($this->extraConfig[$key][$index])?$this->extraConfig[$key][$index]:'';
        }
        return $value;
    }
}