<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/7/29 0029
 * Time: 下午 3:29
 */

namespace backend\modules\fin\models\contract;


use backend\modules\fin\models\FINBaseForm;
use backend\modules\fin\models\contract\ContractConfig;

class ContractBaseForm extends FINBaseForm
{
    public $uuid;
    public $create_time;
    public $duty_uuid;
    public $duty_name; // 合同负责人，既创建人
    public $money;
    public $status;
    public $start_time;
    public $end_time;
    public $sign_time; // 签约时间
    public $remarks;
    public $part_a_duty; // 甲方负责人
    public $part_a_phone;
    public $part_a_fax;
    public $part_a_address;
    public $part_b_duty; // 乙方负责人
    public $part_b_phone;
    public $part_b_fax;
    public $part_b_address;
    public $path; // 合同存放路劲
    public $template_uuid; // 合同模板
    public $type; //合同类型
    public $config; //合同配置
    public $attachment;
    public $file_name;
    public $code;

    public function rules()
    {
        return [
            [['money','status'],'required'],
            // 金额只能是数字格式，
            [['money'],'number'],
            [
                'file_name',
                'match',
                'pattern'=>'/^[\x{4e00}-\x{9fa5}\w\-\.]{1,30}$/u',
                'message'=>'文件名不能包含特殊字符或长度不宜超过30个字符'
            ],
        ];
    }

    public function init()
    {
        $this->config = (new ContractConfig())->generateConfig();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getList($key) {
        return isset($this->config[$key])?$this->config[$key]:[];
    }

    public function getAppointed($key, $index) {
        return isset($this->config[$key][$index])?
            $this->config[$key][$index]:'';
    }
}