<?php
/**
 * Created by PhpStorm.
 * User: johnny
 * Date: 17-1-5
 * Time: 下午10:55
 */

namespace backend\modules\wom_data\controllers;


use backend\modules\wom_data\models\SupplierDataExchange;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\rest\ActiveController;
use backend\models\helper\ArrayHelper;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\VerbFilter;
use Yii;

class SupplierController extends ActiveController
{
    public $modelClass = '';

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'authenticator' => [
                'class' => CompositeAuth::className(),
                'authMethods' => [
                    HttpBearerAuth::className(),
                    QueryParamAuth::className(),
                ],
            ],
            'verbs'=>[
                'class' => VerbFilter::className(),
                'actions' => [
                    'add-supplier' => ['post'],
                    'update-supplier'=>['post'],
                ],
            ]
        ]);
    }

    public function actions()
    {
        return [];
    }

    public function actionAddSupplier() {
        $formData = Yii::$app->getRequest()->post();
        return (new SupplierDataExchange())->insertRecord($formData);
    }

    public function actionUpdateSupplier() {
        $formData = Yii::$app->getRequest()->post();
        return (new SupplierDataExchange())->updateRecord($formData);
    }

    public function checkAccess($action, $model = null, $params = [])
    {
        parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }
}