<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/7/18 0018
 * Time: 下午 4:50
 */

namespace backend\modules\crm\models\customer\record;


use backend\models\interfaces\DeleteMapRecord;
use backend\models\interfaces\PrimaryTable;
use backend\models\interfaces\RecordOperator;
use backend\models\UUID;
use backend\modules\crm\models\project\record\ProjectContactMap;
use backend\modules\fin\models\FINBaseForm;
use backend\modules\fin\models\FINBaseRecord;
use yii\db\Exception;
use yii\helpers\Json;
use Yii;

class CustomerContactMap extends CustomerBaseRecord implements RecordOperator,DeleteMapRecord
{
    static public function tableName()
    {
        return self::CRMCustomerContactMap;
    }

    public function updateRecord($formData)
    {

    }

    public function updateContact($formData) {
        if(empty($formData)) {
            return false;
        }

        $record = self::find()->andWhere([
            'contact_uuid'=>$formData['uuid'],
            'customer_uuid'=>$formData['object_uuid']])->one();
        if(empty($record)) {
            return false;
        }

        if(!$this->updatePreHandler($formData, $record)) {
            return false;
        }

        $transaction = Yii::$app->db->beginTransaction();
        try{
            $contact = new Contact();
            $contact->updateContact($formData);
            $record->update();
        } catch(Exception $e) {
            $transaction->rollBack();
            throw $e;
            return false;
        }
        $transaction->commit();
        return true;
    }

    public function insertRecord($formData)
    {
        if(empty($formData) || !isset($formData['customer_uuid']) || empty($formData['customer_uuid'])) {
            return true;
        }
        $this->customer_uuid = $formData['customer_uuid'];
        if(isset($formData['contactUuids']) && !empty($formData['contactUuids'])) {
            $contactUuids = Json::decode($formData['contactUuids']);
            $transaction = Yii::$app->db->beginTransaction();
            Try{
                foreach($contactUuids as $type => $uuids) {
                    foreach($uuids as $uuid => $index) {
                        $data = [
                            'customer_uuid'=>$formData['customer_uuid'],
                            'type'=>$type,
                            'contact_uuid'=>$uuid,
                        ];
                        $this->insertSingleRecord($data);
                    }
                }

            } catch(Exception $e) {
                $transaction->rollBack();
                throw $e;
                return false;
            }
            $transaction->commit();
        }
        return true;
    }

    public function recordPreHandler(&$formData, $record = null)
    {
        if(empty($record)) {
            $this->setOldAttribute('customer_uuid',null);
            $this->setOldAttribute('contact_uuid',null);
            $this->setOldAttribute('created_uuid',null);
            $this->setOldAttribute('type',null);
        }
    }

    public function insertSingleRecord($formData) {
        if(empty($formData)) {
            return false;
        }
        if ($this->updatePreHandler($formData)) {
            return $this->insert();
        }

        return false;
    }

    public static function deleteRecordByContactUuid($uuid) {
        return self::deleteAll([
            'contact_uuid'=>$uuid,
        ]);
    }

    public function updateSingleRecord($formData)
    {
        if (empty($formData)) {
            return true;
        }
        $record = self::find()->andWhere([
            'customer_uuid'=>$formData['customer_uuid'],
            'contact_uuid'=>$formData['contact_uuid'],
        ])->one();
        if (!empty($record) && $this->updateRecordBuilder($formData, $record)) {
            return $record->update();
        }

        return false;
    }

    public function formDataPreHandler(&$formData, $record)
    {
        if (empty($record)) {
            if(!isset($formData['uuid']) || empty($formData['uuid'])) {
                $formData['uuid'] = UUID::getUUID();
            }
            if(!isset($formData['contact_uuid']) || empty($formData['contact_uuid'])) {
                $formData['contact_uuid'] = $formData['uuid'];
            }
            $this->clearEmptyField($formData);
        }
        if(isset($formData['object_uuid']) && !empty($formData['object_uuid'])) {
            $formData['customer_uuid'] = $formData['object_uuid'];
            unset($formData['object_uuid']);
        }
        parent::formDataPreHandler($formData, $record); // TODO: Change the autogenerated stub
    }

    public function insertContact($formData) {
        if(empty($formData)) {
            return false;
        }

        if(!$this->updatePreHandler($formData)) {
            return false;
        }
        $transaction = Yii::$app->db->beginTransaction();
        try {
            $contact = new Contact();
            if($contact->insertContact($formData)) {
                $this->insert();
            }
        } catch(Exception $e) {
            $transaction->rollBack();
            throw $e;
            return false;
        }

        $transaction->commit();
        return true;
    }

    public function deleteSingleRecord($uuid1, $uuid2)
    {
        if(empty($uuid1)) {
            return false;
        }

        $record = self::find()->andWhere(['contact_uuid'=>$uuid1, 'customer_uuid'=>$uuid2])->one();
        if(empty($record)) {
            return true;
        }

        $transaction = Yii::$app->db->beginTransaction();
        try {
            $record->delete();
            ProjectContactMap::deleteRecordByContactUuid($uuid1);
            $contact = new Contact();
            $contact->deleteRecord($uuid1);
        } catch(Exception $e) {
            $transaction->rollBack();
            throw $e;
            return false;
        }

        $transaction->commit();
        return true;
    }

    public function getRecordByUuid($uuid1,$uuid2) {
        if(empty($uuid1)) {
            return null;
        }

        $record = self::find()
            ->alias('t1')
            ->select('*')
            ->leftJoin(self::CRMContact . ' t2', 't1.contact_uuid=t2.uuid')
            ->andWhere(['t1.contact_uuid'=>$uuid1, "t1.customer_uuid"=>$uuid2])
            ->asArray()->one();
        if(empty($record)) {
            return null;
        }
        if(isset($record['customer_uuid'])) {
            $record['object_uuid'] = $record['customer_uuid'];
            unset($record['customer_uuid']);
        }
        return $record;
    }
}