<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/7/22 0022
 * Time: 下午 4:19
 */

namespace backend\modules\crm\models\customer\record;


use backend\models\interfaces\Map;
use backend\models\interfaces\RecordOperator;
use backend\models\MyPagination;
use backend\modules\crm\models\CRMBaseRecord;
use Yii;
use backend\modules\rbac\model\RBACManager;

class CustomerTouchRecordMap extends CRMBaseRecord implements RecordOperator,Map
{
    static public function tableName()
    {
        return self::CRMCustomerTouchRecordMap;
    }

    public function allTouchRecord() {
        $condition = [];
        if(Yii::$app->getUser()->getIdentity()->getUserName() != 'admin') {
            $uuids = $this->getOrdinateUuids(RBACManager::CustomerModule);
            $condition = [
                'in',
                't6.sales_uuid',
                $uuids
            ];
        }
        return $this->touchRecordList($condition);
    }
    
    public function listFilter($filter) {
        if(empty($filter)) {
            return $this->allTouchRecord();
        }

        $this->handlerFormDataTime($filter,'min_time');
        $this->handlerFormDataTime($filter,'max_time');

        $map = [
            'customer_name'=>[
                'like',
                't3.name',
            ],
            'follow_name'=>[
                'like',
                't4.name'
            ],
            'min_time'=>[
                '>=',
                't2.time'
            ],
            'max_time'=>[
                '<=',
                't2.time'
            ],
        ];
        $condition = [
            'and'
        ];
        if(Yii::$app->getUser()->getIdentity()->getUserName() != 'admin') {
            $uuids = $this->getOrdinateUuids(RBACManager::CustomerModule);
            $condition[] = [
                'in',
                't6.sales_uuid',
                $uuids
            ];
        }
        
        foreach ($filter as $key => $value) {
            $condition[] = [
                $map[$key][0],
                $map[$key][1],
                $value
            ];
        }

        return $this->touchRecordList($condition);
    }

    public function touchRecordList($condition) {
        $query = self::find()->alias('t1')->select([
            't2.*',
            't3.name customer_name',
            't4.name follow_name',
            't5.name contact_name',
        ])->leftJoin(self::CRMTouchRecord . ' t2', 't1.touch_record_uuid = t2.uuid')
            ->leftJoin(self::CRMCustomerBasic . ' t3', 't1.customer_uuid = t3.uuid')
            ->leftJoin(self::EmployeeBasicInformationTableName . ' t4', 't2.follow_uuid = t4.uuid')
            ->leftJoin(self::CRMContact . ' t5', 't5.uuid = t2.contact_uuid')
            ->leftJoin(self::CRMCustomerAdvance . ' t6', 't6.customer_uuid = t3.uuid')
            ->andWhere($condition);
        $pagination = new MyPagination([
            'totalCount'=>$query->count(),
            'pageSize' => self::PageSize,
        ]);
        $publicCustomerList = $query->orderBy([
            't2.time'=>SORT_DESC
        ])->offset($pagination->offset)->limit($pagination->limit)->asArray()->all();
        $data = [
            'pagination' => $pagination,
            'touchRecordList'=> $publicCustomerList,
        ];
        return $data;
    }

    public function updateRecord($formData)
    {
        // TODO: Implement updateRecord() method.
    }

    public function insertRecord($formData)
    {
        // TODO: Implement insertRecord() method.
    }

    public function updateSingleRecord($formData)
    {
        // TODO: Implement updateSingleRecord() method.
    }

    public function formDataPreHandler(&$formData, $record)
    {
        parent::formDataPreHandler($formData, $record); // TODO: Change the autogenerated stub
    }

    public function insertSingleRecord($formData)
    {
        if(empty($formData)) {
            return true;
        }

        if(!$this->updatePreHandler($formData)) {
            return true;
        }

        return $this->insert();
    }
}