<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/9/13 0013
 * Time: 下午 4:00
 */

namespace backend\modules\daily\models\regulation;


use backend\models\Config;

class RegulationConfig extends Config
{
    const TypeStandard = 1;
    const TypeRegulation = 2;
    const TypeExecuteRule = 3;
    const TypeOther = 4;
    public $extraConfig;
    public function init()
    {
        $this->key = 'regulation_config';
        $this->extraConfig = [
            'type'=>[
                self::TypeStandard => '标准文档',
                self::TypeRegulation => '规章制度',
                self::TypeExecuteRule => '执行规范',
                self::TypeOther => '其他',
            ],
            'enable'=>[
                Regulation::Enable => '有效',
                Regulation::Disable => '过期',
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function updateConfig($formData)
    {
        // TODO: Implement updateConfig() method.
    }

    public function getList($key)
    {
        $list =  parent::getList($key);
        if(empty($list)) {
            $list = isset($this->extraConfig[$key])?$this->extraConfig[$key]:[];
        }
        return $list;
    }

    public function getAppointed($key, $index)
    {
        $value =  parent::getAppointed($key, $index);
        if(empty($value)) {
            $value =  isset($this->extraConfig[$key][$index])?$this->extraConfig[$key][$index]:'';
        }
        return $value;
    }
}