<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/9/1 0001
 * Time: 下午 4:34
 */

namespace backend\modules\crm\models\project\record;


use backend\models\interfaces\Map;
use backend\models\interfaces\RecordOperator;

class ProjectBusinessMap extends ProjectBaseRecord implements RecordOperator,Map
{
    public static function tableName()
    {
        return self::CRMProjectBusinessMap;
    }

    public function insertRecord($formData)
    {
        // TODO: Implement insertRecord() method.
    }

    public function formDataPreHandler(&$formData, $record)
    {
        parent::formDataPreHandler($formData, $record); // TODO: Change the autogenerated stub
    }

    public function insertSingleRecord($formData)
    {
        if (empty($formData) || !isset($formData['project_uuid']) || empty($formData['project_uuid'])) {
            return true;
        }

        if(!$this->updatePreHandler($formData)) {
            return true;
        }

        return $this->insert();
    }

    public function updateRecord($formData)
    {
        // TODO: Implement updateRecord() method.
    }

    public function updateSingleRecord($formData)
    {
        if(empty($formData) || !isset($formData['project_uuid']) || empty($formData['project_uuid'])) {
            return true;
        }

        $record = self::find()->andWhere(['project_uuid'=>$formData['project_uuid']])->one();
        $flag = $this->updatePreHandler($formData, $record);
        if(!empty($record) && $flag) {
            return $record->update();
        } elseif($flag) {
            return $this->insert();
        }
        return true;
    }
}