<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/7/3 0003
 * Time: 下午 5:22
 */

namespace backend\modules\hr\models;

use backend\modules\hr\models\HrBaseForm;
class EmployeeForm extends HrBaseForm
{
    public $uuid;
    public $username;                       //用户名
    public $password;                       //密码
    public $name;                           //姓名
    public $english_name;                   //英文名字
    public $gender;                         //性别
    public $phone_number;                    //电话号码
    public $email;
    public $work_email;                      //工作邮箱
    public $qqNumber;
    public $weichat_number;
    public $education_degree;                //学位
    public $graduated_school;
    public $profession;                     //专业
    public $entry_time;                      //入职时间
    public $out_time;                        //离职时间
    public $status;                          //员工状态
    public $positionName;                        //职位
    public $positionUuid;
    public $departmentLevel;                // 部门等级
    public $department;                     //部门
    public $hukou_category;                  //户口类型
    public $house_fund_number;                //住房公积金账号
    public $id_card_number;                   //身份证号码
    public $type;                            //员工类型 （0 实习生 1 全职 2 兼职 3 顾问）
    public $residence_permit_number;         //居住证号码
    public $qq_number;
    public $address;
    public $hukou_address;
    public $remarks;
    public $attachment;
    public $marriage_status;
    public $generation_status;
    public $ethnic;
    public $emergency_contact;
    public $emergency_contact_phone;
    public $become_full_member_time;
    public $photo;
    public $code; //员工编号


    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    static public function educationDegreeList() {
        return [
            1=>'博士',
            2=>'硕士',
            3=>'本科',
            4=>'大专',
            5=>'高中',
            6=>'初中',
            7=>'小学',
        ];
    }

    static public function employeeStatusList() {
        return [
            1 => '待入职',
            2 => '试用期',
            3 => '在职',
            4 => '离职',
            5 => '实习',
        ];
    }

    static public function employeeTypeList() {
        return [
            1 => '顾问',
            2 => '全职',
            3 => '兼职',
            4 => '实习',
        ];
    }

    static public function hukouCategoryList() {
        return [
            1 => '农村户口',
            2 => '城市户口',
        ];
    }

    static public function marriageStatusList() {
        return [
            1=>'未婚',
            2=>'已婚',
        ];
    }

    static public function generationStatusList() {
        return [
            1=>'未育',
            2=>'已育',
        ];
    }
}