<?php
namespace backend\modules\daily\models\week_report;
use backend\models\Config;

/**
 * Created by PhpStorm.
 * User: johnny
 * Date: 16-11-28
 * Time: 下午4:41
 */
class WeekReportConfig extends Config
{
    const IsCurrentWeekReport = 1; // 本周已完成工作
    const IsNextWeekReport = 2; // 下周计划
    public function init()
    {
        $this->key = 'week_report_config';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function updateConfig($formData)
    {
        // TODO: Implement updateConfig() method.
    }
}