<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/8/15 0015
 * Time: 下午 7:25
 */

namespace backend\modules\crm\models\part_time\model;


use backend\modules\crm\models\CRMBaseRecord;
use yii\helpers\Json;
class PartTimeForm extends CRMBaseRecord
{
    public $name;
    public $status;
    public $gender;
    public $position;
    public $check_status;
    public $attachment;
    public $file_name;
    public $english_name;
    public $phone;
    public $qq;
    public $wechat;
    public $email;
    public $description;
    public $remarks;
    public $refuse_reason;
    public $code;
    public $manager_name;
    public $config;
    public $rules = [
                [['name','phone'],'required'],
                [['phone'],'unique','message'=>'已占用'],
                ['email','email','message'=>'邮箱格式错误'],
                ['qq','number']
            ];
    const codePrefix = "J";
    public function rules()
    {
        return $this->rules;
    }

    public function init()
    {
        $this->config = new PartTimeConfig();
        $this->config->config = $this->config->generateConfig();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function tableName()
    {
        return self::CRMPartTime;
    }

    public function generateCode() {
        $config = $this->config->config;
        if(!isset($config['code'])) {
            $config['code'] = date('y',time()) . '0001';
            $this->config->updateDateConfigByJsonString(Json::encode($config));
        } else {
            $priCode =  date('y',time()) . '0001';
            $lastCode = $config['code'];
            $code = $priCode >= $lastCode ? $priCode:$lastCode;
            $config['code'] = $code;
            $this->config->updateDateConfigByJsonString(Json::encode($config));
        }

        return $code;
    }
}